### ISSUE TITLE
F12 shortcut not working anymore

### ISSUE THREAD

**Issue by heiserhorn** [ddterm/gnome-shell-extension-ddterm#117]
I have been running ddterm for some time in my Debian Sid laptop.

A few days ago after an update the F12 key stopped dropping the terminal down and started opening a new file manager window.

The F12 is still listed in ddterm preferences window and it is not listed in gnome shortcuts or the file manager shortcuts.

Any thoughts where I could look to fix this?

Cheers

**Comment by pmoralesp** [comment]
I'm also facing similar problem. From time to time, F12 stops working randomly. Sometime at startup, other times in middle of session. Only workaround that I founded, was disable and re-enable this extension. It seems that key binding was the problem, but I don't know where look for some logs.

**Comment by amezin** [comment]
This issue contains no information that could help debug and fix the problem. If the problem is still present, please open a new issue.

> The F12 is still listed in ddterm preferences window and it is not listed in gnome shortcuts or the file manager shortcuts.

Yes, this is expected.

> Any thoughts where I could look to fix this?

`journalctl --user`. Also try to open ddterm through command line, as described here: https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/docs/cmdline.md

> From time to time, F12 stops working randomly. Sometime at startup, other times in middle of session. Only workaround that I founded, was disable and re-enable this extension.

Looks like another extension that "overwrites" the keybinding.

Or maybe the application just hangs... But in this case, disabling and reenabling wouldn't help likely.

Sorry, I somehow overlooked this bug report at the time when it was relevant
