### ISSUE TITLE
"Too much recursion"

### ISSUE THREAD

**Issue by jthrilly** [ddterm/gnome-shell-extension-ddterm#164]
Hi! 

On PopOS 22.04, Gnome 42.2.

For the last few weeks I've been experiencing an issue where this extension will become disabled, with the error message "too much recursion" showing up in the gnome extensions configuration app.

Not sure how to help debug the issue, but happy to provide any additional information you might need

**Comment by amezin** [comment]
I have some guesses... But to figure out what's really going on, I'll need the output of:

`dconf dump /com/github/amezin/ddterm/ >dconf.txt`

`journalctl --user -b >journal.txt`

Please run these commands after the bug occurred and upload the generated `dconf.txt` and `journal.txt`.

Does it happen every time you open extension settings, or only sometimes?

And, just in case: the "Preferences" window, that you can open from the context menu, provides access to exactly the same settings. You could use it instead until the bug is fixed.

**Comment by jthrilly** [comment]
> Does it happen every time you open extension settings, or only sometimes?

The issue isn't caused by opening the extension settings - I just saw the error message there when I went to see why the extension had become disabled. I can't access the preferences window either, for the same reason.

Just to be clear, the extension just seems to randomly start working. :man_shrugging:

There's quite a bit of semi-sensitive data in journalctl. Can I email it to you? 

[dconf.txt](https://github.com/ddterm/gnome-shell-extension-ddterm/files/9352964/dconf.txt)

**Comment by amezin** [comment]
Could you remove that semi-sensitive data from the log? It would be a better solution

Otherwise - yes, you could send the log file to mezin.alexander@gmail.com

**Comment by jthrilly** [comment]
I've sent the log, as requested.

One observation is that the extension is back and working as normal after a reboot, with no issues. This machine runs 24/7, so perhaps the cause is being triggered by long runtime? Alternatively, I do seem to have some issues with display port negotiation between my monitor and GPU. Sometimes my X11 session doesn't come back up. These are just random conjecture.

**Comment by amezin** [comment]
Could you try this build: [ddterm@amezin.github.com.shell-extension.zip](https://github.com/ddterm/gnome-shell-extension-ddterm/files/9364964/ddterm%40amezin.github.com.shell-extension.zip)?

**Comment by jthrilly** [comment]
Yep this fixes it. I see it was caused by my dodgy monitor causing displayport disconnects.
