### ISSUE TITLE
Make panel icon configurable

### ISSUE THREAD

**Issue by pesader** [ddterm/gnome-shell-extension-ddterm#323]
On some third-party icon themes the current panel icon doesn't look like an icon you would typically find in the panel but do  provide an icon that does. Here's an example with the very popular Papirus icon theme:

| `utilities-terminal` | `utilities-terminal-symbolic` |
|-|-|
| ![Screenshot from 2023-01-29 20-45-15](https://user-images.githubusercontent.com/65264536/215363884-6c7c3e54-25dd-425a-87fc-3b846c95c7f4.png) | ![Screenshot from 2023-01-29 20-46-45](https://user-images.githubusercontent.com/65264536/215363881-691f35fc-0e75-4a7a-9a4d-56509b400cc3.png)|

I would be nice to be able to configure that in the Panel preferences.

**Comment by amezin** [comment]
Hm... Should the icon always be `utilities-terminal-symbolic`? (or is there some weird way to apply `-symbolic` automagically, like in https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/ddterm/app/style.css )

**Comment by zleonov** [comment]
Hi @amezin, first just wanted to say what a cool extension. I use it often.

I came here to make a feature request and I see that it is already here.

1) The default icon should always be `utilities-terminal-symbolic`, I manually change it in panelicon.js
2) It should be configurable in the settings.

This look out of place:
![ddterm-regular](https://github.com/ddterm/gnome-shell-extension-ddterm/assets/6221648/8806ea70-d47b-4f4f-ac2c-be8c859b98d9)

This looks correct:
![ddterm-symbolic](https://github.com/ddterm/gnome-shell-extension-ddterm/assets/6221648/19a32e98-3b62-420d-81bb-a3e50d1db2bc)

**Comment by amezin** [comment]
https://github.com/GNOME/gnome-shell/blob/69ec2156bf068621eab3840e51fbf7f66227084d/data/theme/gnome-shell-sass/widgets/_panel.scss#L35 "symbolic" icon style can be applied with css, just like in Gtk.

It should be an option (checkbox) - because, for example, appindicator icons aren't "symbolic".

I'm not sure if the ability to override the icon name is actually necessary.

Anyway, there seems to be no tricky/non-trivial logic, pull requests are welcome.
