### ISSUE TITLE
screen splitting

### ISSUE THREAD

**Issue by maxadamo** [ddterm/gnome-shell-extension-ddterm#42]
either Guake, Tilix, Terminator... support terminal splitting (see below screenshot) which is useful, if I run tail against multiple log files. 

![immagine](https://user-images.githubusercontent.com/1710103/118406286-b3e08300-b67b-11eb-8bae-b2c4ff9cd2db.png)

**Comment by amezin** [comment]
This is definitely doable. But as I don't need this feature myself, I'm not sure if I'll have time to work on it

**Comment by maxadamo** [comment]
This is a real use case for me and this is how I watch logs contemporarily on multiple servers (and for now I am using another Quake application, which allows me to use Terminator): 
![immagine](https://user-images.githubusercontent.com/1710103/123562286-15812a80-d7ae-11eb-8732-51399a406be3.png)

**Comment by gorogm** [comment]
This would be really nice to have, I would use it frequently. This is probably the only missing feature to reach yakuake and others

**Comment by maxadamo** [comment]
On a side note, it would be interesting to understand what is the most common use case for Quake terminals. 
I use it only to watch logs, and since we have big monitors, splitting the terminal seems sensible.

**Comment by amezin** [comment]
Two (top-level, i. e. X11/Wayland) or more windows are a really bad idea. The extension (wm part) is already a big pile of hacks that I don't fully understand myself. I'm able to maintain it in a somewhat working state only because of extensive testing (both automated and manual). I'm not even adding things like configurable width https://github.com/amezin/gnome-shell-extension-ddterm/issues/67 because, with the current state of things, it will be a testing nightmare.

The correct way here is to split `appwindow.{ui,js}` into two parts:

1) the window itself
2) GtkNotebook with all its corner buttons and other stuff

And, as the first step, add a GtkPaned into the window, then create two notebook instances and add them into the GtkPaned (so one split max).

If necessary, it will be possible to build a full tiling manager on top of this later. But at first, the solution with two panes should be working.

**Comment by amezin** [comment]
@jacksongoode are you going to implement it, or just asking? :)

I see that multiple people want this feature... But I don't need it myself, so it's unlikely that I'll work on it

**Comment by scarlion1** [comment]
Is there a way to have more than one split, or would adding that not be too difficult now that the initial splitting was implemented?  Thx
