### ISSUE TITLE
Can't toggle ddterm open

### ISSUE THREAD

**Issue by alejoguitar** [ddterm/gnome-shell-extension-ddterm#597]
### GNOME Shell version

44.2

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [X] High DPI
- [X] More than one monitor

### ddterm version

46

### Linux distro

"NixOS 23.05 (Stoat)"

### ddterm settings dump

```ini
force-x11-gdk-backend=false
hide-when-focus-lost=false
panel-icon-type='toggle-and-menu-button'
show-animation='linear'
tab-label-width=0.25
tab-policy='automatic'
window-monitor='focus'
window-monitor-connector='DVI-I-1'
window-resizable=true
window-skip-taskbar=false
```

### Description

Tried many config options, but I can't get to see the terminal, either by pressing f12 or clicking on the panel button.
When toggling from the panel buton, i get this on jounralctl -.b
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                               toggle@/home/alejo/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/appcontrol.js:210:17
                                               create_panel_icon/<@/home/alejo/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/extension.js:174:25
                                               set type_name/<@/home/alejo/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/panelicon.js:256:22
                                               _init/<@/home/alejo/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/panelicon.js:72:18
                                               toggle@resource:///org/gnome/shell/ui/popupMenu.js:431:14
                                               activate@resource:///org/gnome/shell/ui/popupMenu.js:418:18
                                               vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:146:14

When doing from the hotley, this comes on
JS ERROR: Failed to toggle ddterm by keybinding: Error: com.github.amezin.ddterm: subprocess terminated without registering on D-Bus
                                             start/terminated<@/home/alejo/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/service.js:180:23
                                             
not the slightest idea what to do. I've been using ddterm for a year or more, in several systems, now that I moved to NixOS apparently it's having this problem.

Thanks for this awesome software!

**Comment by amezin** [comment]
What happens if you run `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm` (from GNOME Terminal/Console)?

**Comment by alejoguitar** [comment]
I suspected it could be related to some NixOS shennanigans. I get:
/usr/bin/env: ‘gjs’: No such file or directory

Not sure if there's something I can do to fix it, or work around the issue. I only started using NixOS this week. Probably creating as symlink?

**Comment by amezin** [comment]
It means `gjs` isn't in `PATH`. Which is weird - it's a dependency of GNOME Shell.

Seems that they repackage ddterm: https://github.com/NixOS/nixpkgs/issues/259035 so if the latest available version, you may have to wait, or ping the maintainers there.

**Comment by TheRealGramdalf** [comment]
Just thought I'd add my experience on this @alejoguitar and @amezin:

NixOS does indeed repackage ddterm - it's because of how NixOS works. The maintainer of the nixpkgs (repackage) is aware, but due to some unfortunate timing of the library experiment and Gnome 45 breaking all the extensions, the latest version (of ddterm) available in nixpkgs is v43 - and because of the peculiarities of gnome and nixos, it needs some metadata to be changed for it to run properly. I've reopened the [issue](https://github.com/NixOS/nixpkgs/issues/259035) about ddterm in nixpkgs asking if it can be updated to v45, so we'll have to wait and see.

This is more for amezin's benefit, but here's the reason for `gjs` not being found:

NixOS uses a combination of immutability and pseudo-containerisation to separate each program you run. Similar to flatpak, NixOS keeps common dependencies in it's "store" - so in this case, gjs. At runtime, the `PATH` variable is modified with only the dependencies needed for a specific application, and at whatever version is known to work - a sort of pseudo-containerization.
Due to the way gnome extensions work, I'm guessing that ddterm doesn't declare `gjs` as a dependency, and assumes that `gnome-shell` provides `gjs` (and rightly so, in most cases). Since the last version available in nixpkgs is v43, I assume there's some dependency issue - not sure exactly what, `piegamesde` would be able to tell you. In any case, since the nixpkgs (ddterm) version is out of sync with the gnome version, gjs isn't added to path properly on runtime, and thus throws `/usr/bin/env: ‘gjs’: No such file or directory`.

As far as immutability, NixOS is typically configured entirely from one file (though you can branch it out to use multiple files or choose not to manage everything declaratively with your nix config), and NixOS works some magic and creates a digitally identical system - with the right preparation, you can have a cryptographically identical (primarily using SHA checksums) system.*
The Nix Store (where all the dependency/program data is installed and housed) is immutable - so you get a lot of the benefits of an immutable system without a lot of the downsides.**

*Of course there are exceptions - logs and other runtime files won't be the same, but you can use a single plain text file to declare your software
**This is a simplified explanation, exact details may not be correct in all cases

**Comment by alejoguitar** [comment]
Hello @TheRealGramdalf  and thanks for your detailed answer. 
I'm new to NixOS (I know this is not the place to have this conversation so I'll keep it short) and I got like an 80% of your explanation. 
I tried installing ddterm all the ways of those suggested on the wiki, but I could only get to install it doing it from the browser. Isn't there a temporary workaround, like wrapping the extension so it can have gjs on its's path, or even listing gjs as a user package? or using version 43?

Other "quake" terminals didn't worked either... not sure how big is the ddterm userbase on NixOS, maybe I'll just have to wait. It'll just be a little annoying to me because it's the main way I use the terminal.

**Comment by amezin** [comment]
@alejoguitar I believe you have two options:

1) Install ddterm as nix package
2) Make sure gjs is symlinked (or available in some other meaning) in one of PATH directories

I guess you should be able to achieve (2) by editing your configuration.

Anyway, it doesn't look like I could do anything to improve the situation here. Feel free to create a PR with Nix packaging scripts if you write them.

**Comment by TheRealGramdalf** [comment]
@alejoguitar The easiest solution would be to just wait. Gnome 45 is set to release along with NixOS 23.11, which is currently aiming for around the end of November. It should be fixed by then, but no guarantees. 

If it is possible to patch it with a derivation or otherwise, I'll definitely let you know. You may also want to follow [this issue(https://github.com/NixOS/nixpkgs/issues/259035), which may have additional information.

**Comment by alejoguitar** [comment]
Thanks so much @amezin and @TheRealGramdalf . I'll be following the Nix issue, and while I wait, I'll be using guake which, though not as close as aestetichally pleasing, does the job. 
I can confirm that installing the extension as nix packaget (which is in fact a neater solution) doesn't work either. Extension is installed, but can't be activated and it's marked with a red clock icon.

**Comment by piegamesde** [comment]
It looks like 0a263a15a6ac82274ebf3e4f6b98e7b226e8188a was made in an attempt to fix this, however it turns out that makes things even harder for us. I am not 100% confident about this, but to me it looks like this issue was purely a downstream one which would have needed no upstream intervention.

I think it would be easiest to simply revert 0a263a15a6ac82274ebf3e4f6b98e7b226e8188a again and deal with the issue in the downstream NixOS packaging. Apologies for the inconvenience.

**Comment by amezin** [comment]
Commit 0a263a15a6ac82274ebf3e4f6b98e7b226e8188a affects only this dialog https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/docs/screenshots/deps-package.png - which starts in a separate process. I just tried to make sure the same GJS binary is used to start that helper script/process.

It has no effect when all gir dependencies are installed.

Why does this change make things worse? Is `get_interpreter()` output incorrect?

And, anyway, `ddterm/app/dependencies-notification.js` should be useful only for installations from extensions.gnome.org. If installing from a distro-specific package, the package should pull all necessary dependencies - and `dependencies-notification.js` will never be called.

By the way, ddterm also needs Perl or Python in `PATH` - https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/ddterm/app/tcgetpgrp.js

**Comment by amezin** [comment]
> So the issue is that the commit now calls the file as a script, whereas previously it was an executable with a shebang. Patching shebangs is significantly easier, since there is already automated tooling for that.

Why would you want to patch `dependencies-notification.js` at all?

If the app fails to start because of a missing dependency, it spawns `dependencies-notification.js`, with the same gjs that the app itself was started with (with the one `/proc/pid/cmdline` points to).

What you need to patch is https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/bin/com.github.amezin.ddterm - `exec gjs` line. It's the interpreter that will run the app. If it's inconvenient - I'm open to suggestions how to make patching there easier.

> If this feature is only relevant for user installations anyways, would there maybe a way to patch the entire thing out instead? Would that be easier?

`dependencies-notification.js` won't be called if everything is installed correctly. So why touch it at all?

Plus `dependencies-notification.js` could go away soon.

**Comment by piegamesde** [comment]
> Why would you want to patch dependencies-notification.js at all?

This is a good point tbh

**Comment by TheRealGramdalf** [comment]
@alejoguitar ddterm is now working on my system, but requires me to add `gjs` to my home-manager configuration for it to work properly. 
https://github.com/TheRealGramdalf/.dotsv2/tree/b41062ce414ce35641523cc9fc7b17557eb9b169

**Comment by amezin** [comment]
People from this thread, please look at this issue: https://github.com/ddterm/gnome-shell-extension-ddterm/issues/1203

Maybe someone could write NixOS packaging scripts (flake or how you call it) for ddterm? Not for nixpkgs, but to make ddterm git repository usable?

ddterm uses Meson build system nowadays, and discovers paths to all executables using meson's `find_program()`.
