### ISSUE TITLE
 toggling ddterm doesn't focus into it automatically

### ISSUE THREAD

**Issue by nattyebola** [ddterm/gnome-shell-extension-ddterm#769]
### GNOME Shell version

GNOME Shell 45.0

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [X] More than one monitor

### Extension version

50

### Linux distro

Ubuntu 23.10

### Verbose version information

ddterm 50 revision 751e218ebcea54828dd4357adecf6669daccab5d
Extension 50 revision 751e218ebcea54828dd4357adecf6669daccab5d

### ddterm settings dump

```ini
[/]
background-opacity=0.94999999999999996
command='user-shell'
ddterm-activate-hotkey=['Delete']
ddterm-toggle-hotkey=['<Control>oe']
delete-binding='tty'
hide-animation='disable'
hide-window-on-esc=true
override-window-animation=true
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
panel-icon-type='none'
show-animation='disable'
tab-expand=true
tab-label-ellipsize-mode='middle'
tab-label-width=0.25
tab-policy='always'
tab-position='top'
transparent-background=false
use-system-font=true
window-maximize=false
window-size=0.69351851851851853
```

### Description

when i press the the keyboard shortcut or press on the panel icon, it shows the terminal but doesn't focus into it

**Comment by amezin** [comment]
Do you have any other extensions enabled and/or installed? Since it's Ubuntu, I guess it's at least some kind of dock, and appindicators. However, with stock Ubuntu I'm unable to reproduce the problem.

Which application windows are open when this happens? Does it happen when no application windows are open at all?

**Comment by nattyebola** [comment]
i use vanilla gnome
```bash
$ gnome-extensions list --enabled
weatherornot@somepaulo.github.io
power-profile-switcher@eliapasquali.github.io
screen-rotate@shyzus.github.io
clipboard-indicator@tudmotu.com
appindicatorsupport@rgcjonas.gmail.com
caffeine@patapon.info
ddterm@amezin.github.com
```
I tested by deactivating all extensions and opening no application, same problem.

**Comment by nattyebola** [comment]
I've just noticed that an instance of the gnome terminal was still open, but not listed in my taskbar
(I tested this extension just before yours: https://extensions.gnome.org/extension/6307/quake-terminal/ )
once killed, the problem is solved
sorry for the inconvenience.

**Comment by amezin** [comment]
Soo you mean after disabling/removing quake-terminal you didn't log out (to restart the Shell)?

Usually you should do that with extensions - otherwise there's really no guarantee that previous extensions cleaned up everything after themselves. In theory, they should do it, but in practice, bugs/oversights do exist.

I guess I should add some troubleshooting steps, and things like "please restart the shell before reporting issues" to the bug report form.

**Comment by nattyebola** [comment]
yes, I should have started there, sorry
