### ISSUE TITLE
Instructions for setting ddterm as external terminal (for apps like VSCode)

### ISSUE THREAD

**Issue by jacksongoode** [ddterm/gnome-shell-extension-ddterm#96]
Is there an executable command to open and run from ddterm? This could be used as the prefix for editors who might open an external terminal for the user on run.

**Comment by amezin** [comment]
No, there is no such command. It should not be hard to implement using D-Bus/GAction, but it has to go through the extension first (because ddterm app may not be running, and the app must be started from the extension).

**Comment by mrf345** [comment]
A while ago i added a method to the d-dbus interface, the implementation is a bit hacky since it's using a setting to pass the command to the application, but it's been working so far. I was about to create a PR, but it seems many things has changed since then (`rxjs` introduced), so most of what's there needs to be changed. Unfortunately, I don't have the time to do that, in case someone else is interested https://github.com/mrf345/gnome-shell-extension-ddterm/commit/417ce69cee40220396ed9b265570f0f8a120fb8c

example: `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/ddterm --method com.github.amezin.ddterm.Extension.RunCommand /your/shell/script/path.sh`

**Comment by amezin** [comment]
Now you can create tabs from the command line - for example: `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/com.github.amezin.ddterm --wait -- nano somefile.txt`
